# Generated by Django 5.1.6 on 2025-05-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_userregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="DogBreed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("origin", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="dog_breeds/"),
                ),
            ],
        ),
    ]
