# Generated by Django 5.1.6 on 2025-05-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_dogbreed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                ("login_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
