# Generated by Django 5.1.7 on 2025-06-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_rename_login_logindata"),
    ]

    operations = [
        migrations.AddField(
            model_name="dogbreed",
            name="slug",
            field=models.SlugField(default="example-slug", unique=True),
            preserve_default=False,
        ),
    ]
