# Generated by Django 5.1.6 on 2025-06-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_dogbreed_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
