# Generated by Django 5.1.7 on 2025-06-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0007_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dogbreed",
            name="origin",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
