# Generated by Django 5.1.7 on 2025-06-10 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0008_alter_dogbreed_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="dogbreed",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breeds",
                to="service.category",
            ),
        ),
    ]
