# Generated by Django 5.1.7 on 2025-06-25 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_groomingproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('Sell', 'Sell'), ('Buy', 'Buy')], default='Sell', max_length=10)),
                ('pet_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Fish', 'Fish'), ('Others', 'Others')], max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.DecimalField(decimal_places=1, help_text='Age in years (e.g., 1.5)', max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price or offer', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet_market/')),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_market_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
