# Generated by Django 5.1.6 on 2025-06-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_petmarket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetSittingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('pet_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('SITTING_TYPE_CHOICES', models.CharField(choices=[('home', 'Home Sitting'), ('care', 'Care Centre')], max_length=10)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
