# Generated by Django 5.1.6 on 2025-06-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_petsittingservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsittingservice',
            name='cost',
        ),
    ]
