# Generated by Django 5.1.6 on 2025-06-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_rename_sitting_type_choices_petsittingservice_sitting_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('pet_name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('pre_existing_conditions', models.TextField(blank=True, null=True)),
                ('selected_plan', models.CharField(choices=[('basic', 'Basic Plan'), ('standard', 'Standard Plan'), ('premium', 'Premium Plan')], max_length=10)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
